Upgrade Loyc.Math to support nullability
and try to fix appveyor error due to new benchmark app:

error NETSDK1045: The current .NET SDK does not support targeting .NET 10.0...
error CS0122: 'AllowNullAttribute' [etc] is inaccessible due to its protection level